# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTOAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sloc',
            field=models.CharField(max_length=20),
        ),
    ]
