# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTOAPP', '0002_auto_20190123_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='OTOAPP.Student'),
        ),
    ]
