# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTOAPP', '0003_auto_20190124_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OTOAPP.Student'),
        ),
    ]
