# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTOAPP', '0004_auto_20190124_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abc',
            field=models.OneToOneField(null=True, on_delete=models.SET(3), to='OTOAPP.Student'),
        ),
    ]
